apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m7q2w0v68-nodejs 
  janus-idp.io/tekton: m7q2w0v68-nodejs
  backstage.io/kubernetes-id: m7q2w0v68-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m7q2w0v68-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  