apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m7q2w0v68-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m7q2w0v68-nodejs 
  name: m7q2w0v68-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: m7q2w0v68-nodejs 
